# Generated by Django 5.0.2 on 2024-02-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ProductID',
            field=models.IntegerField(error_messages='Error at the ProductID column of product table'),
        ),
    ]
