# Generated by Django 5.0.2 on 2024-02-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ProductSeq',
            field=models.AutoField(error_messages='Error at the ProductSeq column of product table', primary_key=True, serialize=False),
        ),
    ]
